### ISSUE TITLE
Orbital Market not updating...

### ISSUE THREAD

**Issue by hugoattal** [hugoattal/OrbitalMarket#55]
Yep, I know, since a couple of days, Orbital Market doesn't update any more...

It's because the Unreal marketplace added a Captcha to prevent scrapping.

I have a few ideas to bypass that, but I'm kinda tired of playing cat and mouse. So I'm emailing them to see if they can whitelist the Orbital Market server. After all, it only brings them good stuff since all the traffic is redirected to their marketplace.

I'll let you know about their response.

**Comment by hugoattal** [comment]
(They refused, I found another way)

**Comment by MattL-V** [comment]
Is Orbital again not updating?
Last listed assets are from 3 days ago

**Comment by hugoattal** [comment]
@MattL-V The marketplace API has become a bit unstable/unpredictable. To solve this, here's how Orbital Market now works:

- It retrieves all the products 100 by 100, starting by the oldest to the newest
- If at one point, the retrieving fails, it retries up to 5 times with a few seconds pause between each
- If it works at some point, it continues
- If it fails at the 5th attempt, it saves the page it was trying to process
- On the next batch (every 24h), it restarts at the saved page that it fails on the last batch

The last batch stopped at product 42300 (there are 52k products), so hopefully, it should be finished retrieving all the products on the next batch.

**Comment by MattL-V** [comment]
Considering another 24h passed and the assets haven't been updated, does this mean Orbital failed to retrieve the assets for the last 5 days?
So, theoretically, this can fail again and again, and Orbital will never display the latest assets?
Maybe it would be better to run more often than only once in 24h?

**Comment by hugoattal** [comment]
@MattL-V Seems like it stopped at 52100. Maybe the marketplace blocks Orbital market every 100 pages (10k products) 🤔 ?

> does this mean Orbital failed to retrieve the assets for the last 5 days

No, it means, that it only updated (around) 10k products per day

> So, theoretically, this can fail again and again, and Orbital will never display the latest assets?

Since it saves the progression, Orbital Market will inevitably retrieve the latest assets, likely in the next 24h I guess.

> Maybe it would be better to run more often than only once in 24h?

I believe the more often I run it, the more likely the marketplace will block Orbital Market 😕...

**Comment by hugoattal** [comment]
@MattL-V, as you can see, the latest products are now available on Orbital Market 😉

**Comment by MattL-V** [comment]
Unfortunately, the latest assets are from 9 September.
Was Orbital up to date for a few days and now has a hiccup for over a week? 
Does Orbital retrieve all assets from the oldest one every day, or only the newly released ones?

**Comment by hugoattal** [comment]
You're right, the last week seems to have failed at every single try... I'll check it out, sorry for this 😕

**Comment by hugoattal** [comment]
It should be fixed + I manually triggered the update. Everything should be updated.

I will wait for FAB to make any update of the update process though 🤔

**Comment by MattL-V** [comment]
Can you manually trigger the update again?
I saw you pushed updates to FAB API a few days ago, but the latest assets are still from 1 December and assets still have their Black Friday sale displayed.
Considering that in a few days the Christmas sale starts, it will not be possible to search for assets.

**Comment by hugoattal** [comment]
You're right! I've fixed a few bugs, I'll let the overnight CRON trigger to see if it works. If it does not, I'll fix the bug and try to trigger it manually tomorrow.

**Comment by hugoattal** [comment]
@MattL-V Everything is up to date!

**Comment by MattL-V** [comment]
When I filter for discounted assets, there are still many assets with their Black Friday sale. The strange thing is that if I try to open their FAB page, it goes to "Sorry, we couldn’t find that page." 
Maybe those assets had something changed in their backend during the time and can't update now?

**Comment by hugoattal** [comment]
Aaaaah, what did they do again 😭... I'll have to find time to debug this...

**Comment by MattL-V** [comment]
Unfortunately, it didn't update today 
We can't search for great Christmas deals😭
The start page broke and shows many empty spaces instead of assets.
I tested it on different browsers and PCs.
![Screenshot 2024-12-24 154816](https://github.com/user-attachments/assets/63ea1410-c2cb-4c7a-91bd-12c4bc1d9162)

**Comment by hugoattal** [comment]
Hum, there seems to be a problem with pulling new assets 🤔...

But if you sort by popularity, it' working fine, especially if you're looking for Christmas deals: https://orbital-market.com/search?discount=10-100

To be fair, it's unlikely I'll find the time to fix it this week, given I'm with my family for the holidays 😕

**Comment by MattL-V** [comment]
Hello, I hope you had a great time with your family. 
There are still some issues with the asset retrieval. The "latest released" page is bugged, and many assets that were discounted on Christmas still display as being discounted.

**Comment by hugoattal** [comment]
Right, I'll take a look at this "blank" product bug 🤔...

**Comment by hugoattal** [comment]
I've added a few more things:
- the latest released page should be fixed
- the discount should be updated on the next update

**Comment by MattL-V** [comment]
Hello, in the last 6 days only 2 assets were parsed. And from the days before, only some released assets were parsed. The Christmas sale is still shown as being active on many assets.

**Comment by hugoattal** [comment]
Ok, all the items marked for Christmas sales are actually unlisted on Fab, they might have been taken down.

I need a way to check if the products have been removed from Fab, I have an idea on how to do that, I'll take a shot next week.

**Comment by MattL-V** [comment]
Hello, any updates why Orbital is parsing only a few assets a day and even skips some days completely?

**Comment by hugoattal** [comment]
Orbital Market only skips assets marked as "mature." "Skipped days" are days on which only "mature" assets were released.

**Comment by hugoattal** [comment]
Hum, that's weird, I'll have to investigate once I'll have a little time 🤔...
(btw, since orbital is open source, feel free to try to fix it 🙂)

**Comment by GoldenViperz** [comment]
Hello.

Does Orbital not update frequently anymore?

I tried sorting the top reviewed items for the past month and barely anything shows up, yet when I search on FAB for the passt 30 days there's tons of items with lots of reviews.

Top Unreal releases don't even show up on Orbital like,
https://www.fab.com/listings/75455ba4-7407-45db-b24e-160712b9586c
https://www.fab.com/listings/9473adde-baf1-4401-80a2-5c62e1d2d176
https://www.fab.com/listings/30a24a9f-a722-44f7-b328-474992757891
https://www.fab.com/listings/3f7f3758-fef5-4af9-b7af-d836c2381bda
https://www.fab.com/listings/ce906c8e-6eb3-4692-8a99-6c0d94444b7d

Thank you.

**Comment by hugoattal** [comment]
It updates every 24h, but yeah, it seems like it's missing some products for some reason... I didn't have the time to investigate this yet 😕

**Comment by hugoattal** [comment]
It updates every 24h, but yeah, it seems like it's missing some products for some reason... I didn't have the time to investigate this yet 😕

**Comment by hugoattal** [comment]
I have identified a bug and fix it. I think this should solve it. I'm currently launching another fetch.

**Comment by hugoattal** [comment]
Confirmed, it's fixed 🥳
